import os
import pandas as pd
import ast
import argparse
from utils.evaluation_utils import evaluate_predictions, get_classes_for_model

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Calculate evaluation metrics on a previously generated test output.")
    parser.add_argument("--input_csv", type=str, required=True, 
                        help="Path to the input CSV file. This must be the output CSV file generated by test.py.")
    parser.add_argument("--model", type=str, required=True, 
                        help="Name of a model folder inside 'models' or a full path to it.")
    args = parser.parse_args()

    file_path = args.input_csv
    if not os.path.exists(file_path):
        print(f"Error: Could not find input CSV file at {file_path}")
        exit(1)

    model_arg = args.model
    if os.path.isabs(model_arg) or os.path.exists(model_arg):
        model_path = os.path.abspath(model_arg)
    else:
        model_path = os.path.join("models", model_arg)

    results = None
    
    try:
        df = pd.read_csv(file_path)
            
        df['predicted'] = df['predicted'].apply(ast.literal_eval)
        df['groundtruth'] = df['groundtruth'].apply(ast.literal_eval)
        
        classes = get_classes_for_model(model_path)
        
        results = evaluate_predictions(df['groundtruth'].tolist(), df['predicted'].tolist(), classes=classes)
    except Exception as e:
        print(f"Error processing {file_path}: {e}")
        exit(1)
            
    # Create a DataFrame from the dictionary of dictionaries
    comparison_df = pd.DataFrame(results)
    
    # Reset index so 'Metric' becomes a regular column instead of the index
    comparison_df = comparison_df.reset_index().rename(columns={'index': 'Metric'})
    
    # Format the numbers to 4 decimal places across all model columns
    for col in comparison_df.columns:
        if col != 'Metric':
            comparison_df[col] = comparison_df[col].apply(lambda x: f"{float(x):.4f}")
    
    print(f"=== Multi-Label Evaluation Comparison ===")
    print(comparison_df.to_string(index=False))